services:
  nginx:
    container_name: atelier-nginx
    image: nginx:1.27-alpine
    depends_on:
      - blog-blue
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/includes:/etc/nginx/includes:ro

  blog-blue:
    container_name: atelier-blog-blue
    image: atelier-blog:test
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "127.0.0.1:3001:3000"

  blog-green:
    container_name: atelier-blog-green
    image: atelier-blog:test
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "127.0.0.1:3002:3000"
